version: "3"
services:
  bitcoind:
    image: kylemanna/bitcoind
    command: bitcoind -testnet -rest -rpcport=18332 -rpcallowip=0.0.0.0/16 -rpcuser=user -rpcpassword=pwd -server
    ports:
      - "8332:8332"
      - "18332:18332"
    volumes:
      - ./bitcoindata:/bitcoin
